<?php
namespace App\Http\Controllers\Api\V1;
use App\Http\Controllers\Controller;
use App\Models\TransportPackage;
use App\Models\Trip;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use Illuminate\Validation\ValidationException;
class PackageController extends Controller {
    public function store(Request $request){$d=$request->validate(['trip_id'=>['required','exists:trips,id'],'sender_name'=>['nullable','string','max:150'],'recipient_name'=>['required','string','max:150'],'recipient_phone'=>['nullable','string','max:40'],'recipient_email'=>['nullable','email','max:150'],'description'=>['nullable','string','max:3000']]);$driver=$request->user()?->driver;if(!$driver)return response()->json(['message'=>'Driver profile not found.'],404);$trip=Trip::findOrFail($d['trip_id']);if($request->user()?->role!=='admin'&&$trip->driver_id!==$driver->id)return response()->json(['message'=>'Forbidden.'],403);$token=Str::random(64);$package=TransportPackage::create($d+['public_id'=>(string)Str::uuid(),'tracking_token_hash'=>hash('sha256',$token),'driver_id'=>$driver->id,'reference'=>'PK-'.strtoupper(Str::random(10)),'status'=>'received']);$package->events()->create(['user_id'=>$request->user()?->id,'status'=>'received','occurred_at'=>now()]);return response()->json(['data'=>['package'=>$package->load('trip.route'),'tracking_token'=>$token,'tracking_url'=>'/track-package/?token='.$token]],201);}
    public function updateStatus(Request $request,TransportPackage $package){$d=$request->validate(['status'=>['required','in:received,in_progress,delivered'],'notes'=>['nullable','string','max:2000']]);$driver=$request->user()?->driver;if($request->user()?->role!=='admin'&&(!$driver||$package->driver_id!==$driver->id))return response()->json(['message'=>'Forbidden.'],403);$allowed=['received'=>['in_progress'],'in_progress'=>['delivered'],'delivered'=>[]];if(!in_array($d['status'],$allowed[$package->status]??[],true)&&$d['status']!==$package->status)throw ValidationException::withMessages(['status'=>'Invalid package status transition.']);$package->forceFill(['status'=>$d['status'],'delivered_at'=>$d['status']==='delivered'?now():$package->delivered_at])->save();$package->events()->create(['user_id'=>$request->user()?->id,'status'=>$d['status'],'notes'=>$d['notes']??null,'occurred_at'=>now()]);return response()->json(['data'=>$package->fresh(['trip.route','events'])]);}
    public function track(string $token){$package=TransportPackage::with(['trip.route','events'=>fn($q)=>$q->orderBy('occurred_at')])->where('tracking_token_hash',hash('sha256',$token))->first();if(!$package)return response()->json(['message'=>'Tracking reference not found.'],404);return response()->json(['data'=>['reference'=>$package->reference,'status'=>$package->status,'route'=>$package->trip?->route?->origin&&$package->trip?->route?->destination?$package->trip->route->origin.' → '.$package->trip->route->destination:null,'created_at'=>$package->created_at,'delivered_at'=>$package->delivered_at,'events'=>$package->events->map(fn($e)=>['status'=>$e->status,'notes'=>$e->notes,'occurred_at'=>$e->occurred_at])]]);}
    public function index(Request $request){$q=TransportPackage::with(['trip.route','driver'])->latest();if($request->filled('status'))$q->where('status',$request->status);return response()->json(['data'=>$q->limit(300)->get()]);}
}
