import React, { useState } from 'react';
import { ActivityIndicator, SafeAreaView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
const API=process.env.EXPO_PUBLIC_API_URL ?? 'http://127.0.0.1:8000/api/v1';
export default function App(){
 const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[token,setToken]=useState('');const[driver,setDriver]=useState<any>(null);const[trip,setTrip]=useState<any>(null);const[loading,setLoading]=useState(false);const[error,setError]=useState('');
 const request=async(path:string,options:RequestInit={})=>{const r=await fetch(`${API}${path}`,{...options,headers:{Accept:'application/json','Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})}});const p=await r.json();if(!r.ok)throw new Error(p?.message??`API ${r.status}`);return p};
 const login=async()=>{setLoading(true);setError('');try{const p=await request('/auth/login',{method:'POST',body:JSON.stringify({email,password})});setToken(p.token);const headers={Accept:'application/json',Authorization:`Bearer ${p.token}`};const [d,t]=await Promise.all([fetch(`${API}/driver/me`,{headers}).then(r=>r.json()),fetch(`${API}/driver/trips/current`,{headers}).then(r=>r.json())]);setDriver(d.data);setTrip(t.data??null);}catch(e){setError(e instanceof Error?e.message:'Login failed.')}finally{setLoading(false)}};
 if(!token)return <SafeAreaView style={s.safe}><View style={s.wrap}><Text style={s.brand}>Encore Drive</Text><Text style={s.title}>Driver login</Text><TextInput style={s.input} placeholder="Email" autoCapitalize="none" value={email} onChangeText={setEmail}/><TextInput style={s.input} placeholder="Password" secureTextEntry value={password} onChangeText={setPassword}/><TouchableOpacity style={s.button} onPress={login}><Text style={s.buttonText}>Sign in</Text></TouchableOpacity>{loading&&<ActivityIndicator/>}{!!error&&<Text style={s.error}>{error}</Text>}</View></SafeAreaView>;
 return <SafeAreaView style={s.safe}><View style={s.wrap}><Text style={s.brand}>Encore Drive</Text><Text style={s.title}>{driver?.name??'Driver'}</Text>{trip?<View style={s.card}><Text style={s.cardTitle}>{trip.origin} → {trip.destination}</Text><Text>{trip.date} · {trip.departureTime}</Text><Text>Status: {trip.status}</Text></View>:<Text style={s.empty}>No active or upcoming trip assigned.</Text>}<TouchableOpacity style={s.secondary} onPress={()=>{setToken('');setDriver(null);setTrip(null)}}><Text>Sign out</Text></TouchableOpacity></View></SafeAreaView>;
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#f3f7f9'},wrap:{flex:1,padding:24,gap:12},brand:{fontWeight:'800',color:'#147ca9'},title:{fontSize:30,fontWeight:'800'},input:{backgroundColor:'#fff',borderWidth:1,borderColor:'#d9e4eb',borderRadius:14,padding:14},button:{backgroundColor:'#147ca9',padding:15,borderRadius:14,alignItems:'center'},buttonText:{color:'#fff',fontWeight:'800'},secondary:{borderWidth:1,borderColor:'#d9e4eb',padding:15,borderRadius:14,alignItems:'center'},error:{color:'#a83232'},empty:{color:'#6e7f8e'},card:{backgroundColor:'#fff',borderWidth:1,borderColor:'#d9e4eb',borderRadius:16,padding:16,gap:5},cardTitle:{fontWeight:'800',fontSize:17}});
