import { Ionicons, MaterialCommunityIcons } from '@expo/vector-icons';
import { StatusBar } from 'expo-status-bar';
import { useRef, useState } from 'react';
import { Animated, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import MapView,{Marker,Polyline,PROVIDER_GOOGLE} from 'react-native-maps';
import { SafeAreaProvider,SafeAreaView } from 'react-native-safe-area-context';

type Tab='home'|'trips'|'alerts'|'profile';
type Flow='splash'|'login'|'home'|'boarding'|'active'|'incident'|'complete';
type PassengerState='Boarded'|'Pending'|'Absent';
type Passenger={name:string;seat:string;status:PassengerState};

const c={ink:'#102130',ink2:'#1e394b',muted:'#6e7f8d',line:'#d9e4ea',green:'#1f9d74',blue:'#2da9df',blue2:'#147ca9',amber:'#d39a3b',red:'#d15858',bg:'#eef3f6',white:'#fff'};
const trip={id:'EN-001',origin:'Santo Domingo',destination:'Santiago',departure:'08:30',arrival:'10:45',vehicle:'Bus 203',plate:'A874512',nextStop:'Autopista Duarte checkpoint',passengers:22,seats:40};
const route=[{latitude:18.4822,longitude:-69.9369},{latitude:18.72,longitude:-70.08},{latitude:18.98,longitude:-70.3},{latitude:19.22,longitude:-70.52},{latitude:19.4517,longitude:-70.697}];
const initialPassengers:Passenger[]=[{name:'Maria Torres',seat:'4B',status:'Boarded'},{name:'Luis Ibarra',seat:'4C',status:'Pending'},{name:'Andrea Molina',seat:'5A',status:'Boarded'},{name:'Cecilia Ramos',seat:'6D',status:'Absent'}];

export default function App(){
  const[tab,setTab]=useState<Tab>('home');const[flow,setFlowRaw]=useState<Flow>('splash');const[passengers,setPassengers]=useState(initialPassengers);
  const opacity=useRef(new Animated.Value(1)).current;const y=useRef(new Animated.Value(0)).current;
  const setFlow=(next:Flow)=>{Animated.parallel([Animated.timing(opacity,{toValue:0,duration:90,useNativeDriver:true}),Animated.timing(y,{toValue:12,duration:90,useNativeDriver:true})]).start(()=>{setFlowRaw(next);y.setValue(18);Animated.parallel([Animated.timing(opacity,{toValue:1,duration:180,useNativeDriver:true}),Animated.spring(y,{toValue:0,damping:16,stiffness:180,useNativeDriver:true})]).start()})};
  if(flow==='splash')return <SafeAreaProvider><SafeAreaView style={s.splashSafe}><StatusBar style="light"/><View style={s.splash}><View style={s.splashOrb}><MaterialCommunityIcons name="bus" size={38} color={c.white}/></View><Text style={s.splashBrand}>Encore Driver</Text><Text style={s.splashTitle}>Your trip command center.</Text><Text style={s.splashCopy}>Boarding, route intelligence, vehicle telemetry, incidents and completion in one connected driver experience.</Text><Primary label="Continue" icon="arrow-forward" onPress={()=>setFlow('login')}/></View></SafeAreaView></SafeAreaProvider>;
  if(flow==='login')return <SafeAreaProvider><SafeAreaView style={s.safe}><StatusBar style="dark"/><View style={s.login}><View style={s.loginIcon}><MaterialCommunityIcons name="steering" size={30} color={c.white}/></View><Text style={s.brand}>Encore Driver</Text><Text style={s.title}>Start your shift</Text><Field label="Driver ID" value="ricardo.luna"/><Field label="Access code" value="123456" secure/><View style={s.biometric}><Ionicons name="finger-print" size={24} color={c.blue2}/><View><Text style={s.cardTitle}>Biometric ready</Text><Text style={s.meta}>Future Face ID / fingerprint integration</Text></View></View><Primary label="Enter driver home" icon="log-in-outline" onPress={()=>setFlow('home')}/></View></SafeAreaView></SafeAreaProvider>;
  return <SafeAreaProvider><SafeAreaView style={s.safe} edges={['top','left','right']}><StatusBar style="dark"/><View style={s.app}><Header flow={flow}/><Animated.View style={{flex:1,opacity,transform:[{translateY:y}]}}><ScrollView contentContainerStyle={s.content} showsVerticalScrollIndicator={false}>{tab==='home'&&<Home flow={flow} setFlow={setFlow} passengers={passengers} setPassengers={setPassengers}/>}{tab==='trips'&&<Trips setFlow={setFlow}/>}{tab==='alerts'&&<Alerts setFlow={setFlow}/>}{tab==='profile'&&<Profile/>}</ScrollView></Animated.View><SafeAreaView edges={['bottom']} style={s.navSafe}><BottomNav tab={tab} setTab={setTab}/></SafeAreaView></View></SafeAreaView></SafeAreaProvider>;
}

function Header({flow}:{flow:Flow}){const status=flow==='active'?'On route':flow==='boarding'?'Boarding':flow==='complete'?'Completed':'Available';const title=flow==='home'?"Today's operation":flow==='active'?'Active trip':flow==='boarding'?'Boarding':flow==='incident'?'Incident report':'Trip status';return <View style={s.header}><View><Text style={s.brand}>Encore Driver</Text><Text style={s.title}>{title}</Text></View><View style={[s.statusPill,flow==='active'&&s.statusPillActive]}><View style={[s.statusDot,flow==='active'&&s.statusDotActive]}/><Text style={s.statusText}>{status}</Text></View></View>}

function Home({flow,setFlow,passengers,setPassengers}:{flow:Flow;setFlow:(f:Flow)=>void;passengers:Passenger[];setPassengers:(x:Passenger[])=>void}){
  if(flow==='boarding')return <Boarding passengers={passengers} setPassengers={setPassengers} setFlow={setFlow}/>;
  if(flow==='active')return <ActiveTrip setFlow={setFlow}/>;
  if(flow==='incident')return <Incident setFlow={setFlow}/>;
  if(flow==='complete')return <Complete setFlow={setFlow}/>;
  return <View style={s.stack}>
    <View style={s.command}><View style={s.commandTop}><Text style={s.commandLabel}>Next assigned trip</Text><Text style={s.readyBadge}>READY</Text></View><Text style={s.commandId}>{trip.id}</Text><Text style={s.commandRoute}>{trip.origin} → {trip.destination}</Text><View style={s.metricRow}><Metric icon="time-outline" label="Departure" value={trip.departure}/><Metric icon="bus-outline" label="Vehicle" value={trip.vehicle}/><Metric icon="people-outline" label="Passengers" value={`${trip.passengers}/${trip.seats}`}/></View><Primary label="Start boarding" icon="people-outline" onPress={()=>setFlow('boarding')}/></View>
    <DriverMap compact/>
    <View style={s.telemetry}><Telemetry icon="gas-station" label="Fuel" value="78%" hint="Good"/><Telemetry icon="engine" label="Engine" value="Normal" hint="No alerts"/><Telemetry icon="tire" label="Tires" value="OK" hint="4/4"/><Telemetry icon="access-point" label="Network" value="Online" hint="Live"/></View>
    <View style={s.opsCard}><Text style={s.cardTitle}>Shift overview</Text><Info label="Vehicle inspection" value="Completed · 07:52"/><Info label="Fuel level" value="78%"/><Info label="Operations channel" value="Connected"/></View>
  </View>
}

function Boarding({passengers,setPassengers,setFlow}:{passengers:Passenger[];setPassengers:(x:Passenger[])=>void;setFlow:(f:Flow)=>void}){
  const boarded=passengers.filter(x=>x.status==='Boarded').length;const toggle=(p:Passenger)=>setPassengers(passengers.map(x=>x.name===p.name?{...x,status:x.status==='Boarded'?'Pending':'Boarded'}:x));
  return <View style={s.stack}><View style={s.boardSummary}><View style={s.boardCount}><Text style={s.boardCountText}>{boarded}/{passengers.length}</Text></View><View style={{flex:1}}><Text style={s.cardTitle}>Boarding intelligence</Text><Text style={s.meta}>Passenger state, seat and QR readiness in real time.</Text></View></View>
    <View style={s.scanCard}><View style={s.scanIcon}><MaterialCommunityIcons name="qrcode-scan" size={30} color={c.blue2}/></View><View style={{flex:1}}><Text style={s.cardTitle}>Scan boarding pass</Text><Text style={s.meta}>Camera integration placeholder · tap passenger below for preview.</Text></View><Ionicons name="chevron-forward" size={20} color={c.muted}/></View>
    <View style={s.card}><View style={s.searchBox}><Ionicons name="search" size={18} color={c.muted}/><TextInput style={s.search} placeholder="Search passenger or seat" placeholderTextColor={c.muted}/></View>{passengers.map(p=><Pressable key={p.name} onPress={()=>toggle(p)} style={s.passengerRow}><View style={s.passengerAvatar}><Text style={s.passengerAvatarText}>{p.name.split(' ').map(x=>x[0]).join('')}</Text></View><View style={{flex:1}}><Text style={s.passengerName}>{p.name}</Text><Text style={s.meta}>Seat {p.seat}</Text></View><Text style={[s.passengerStatus,p.status==='Boarded'?s.boarded:p.status==='Absent'?s.absent:s.pending]}>{p.status}</Text></Pressable>)}<Primary label="Start trip" icon="navigate-outline" onPress={()=>setFlow('active')}/></View>
  </View>
}

function ActiveTrip({setFlow}:{setFlow:(f:Flow)=>void}){return <View style={s.stack}>
  <DriverMap/>
  <View style={s.liveCommand}><View style={s.liveTop}><View><Text style={s.commandLabel}>ACTIVE TRIP</Text><Text style={s.cardTitle}>{trip.origin} → {trip.destination}</Text></View><View style={s.live}><View style={s.liveDot}/><Text style={s.liveText}>LIVE</Text></View></View>
    <View style={s.navMetrics}><NavMetric label="ETA" value="10:45"/><NavMetric label="Next" value="42 min"/><NavMetric label="Delay" value="0 min"/></View>
    <Info label="Next stop" value={trip.nextStop}/><Info label="Vehicle" value={`${trip.vehicle} · ${trip.plate}`}/>
    <View style={s.actionRow}><Secondary label="Incident" icon="warning-outline" onPress={()=>setFlow('incident')}/><Primary label="Complete trip" icon="checkmark-circle-outline" onPress={()=>setFlow('complete')}/></View>
  </View>
</View>}

function DriverMap({compact}:{compact?:boolean}){return <View style={[s.map,compact&&s.mapCompact]}><MapView provider={PROVIDER_GOOGLE} style={StyleSheet.absoluteFill} initialRegion={{latitude:18.965,longitude:-70.31,latitudeDelta:compact?1.4:1.15,longitudeDelta:compact?1.4:1.15}} rotateEnabled={false} toolbarEnabled={false}><Polyline coordinates={route} strokeColor={c.green} strokeWidth={5}/><Marker coordinate={route[0]} title="Agora Mall"/><Marker coordinate={route[route.length-1]} title="Monumento"/><Marker coordinate={route[2]} title="Bus 203"><View style={s.busMarker}><MaterialCommunityIcons name="bus" size={18} color={c.white}/></View></Marker></MapView><View style={s.mapOverlay}><View><Text style={s.mapOverlayLabel}>Route EN-001</Text><Text style={s.mapOverlayValue}>Next stop · 42 min</Text></View><View style={s.mapStatus}><View style={s.liveDot}/><Text style={s.mapStatusText}>On schedule</Text></View></View></View>}

function Incident({setFlow}:{setFlow:(f:Flow)=>void}){const[selected,setSelected]=useState('Traffic');return <View style={s.stack}><View style={s.card}><Text style={s.cardTitle}>Report incident</Text><Text style={s.meta}>Operations receives trip, vehicle, driver, timestamp and location automatically.</Text><View style={s.incidentGrid}>{[['Traffic','car-outline'],['Mechanical','construct-outline'],['Passenger','person-outline'],['Route','map-outline'],['Other','ellipsis-horizontal']].map(([x,icon])=><Pressable key={x} onPress={()=>setSelected(x)} style={[s.incidentType,selected===x&&s.incidentActive]}><Ionicons name={icon as any} size={20} color={selected===x?c.white:c.blue2}/><Text style={[s.incidentText,selected===x&&s.incidentTextActive]}>{x}</Text></Pressable>)}</View><TextInput style={s.notes} placeholder="Add details for operations" placeholderTextColor={c.muted} multiline/><Primary label="Send incident preview" icon="send-outline" onPress={()=>setFlow('active')}/></View><DriverMap compact/></View>}

function Complete({setFlow}:{setFlow:(f:Flow)=>void}){return <View style={s.complete}><View style={s.completeHalo}><Ionicons name="checkmark" size={38} color={c.white}/></View><Text style={s.cardTitle}>Trip completed.</Text><Text style={s.metaCenter}>EN-001 arrived in Santiago successfully.</Text><View style={s.completeSummary}><Info label="Passengers" value="22 boarded · 1 absent"/><Info label="Arrival" value={trip.arrival}/><Info label="Distance" value="155 km"/><Info label="Vehicle" value={trip.vehicle}/></View><Primary label="Back to home" icon="home-outline" onPress={()=>setFlow('home')}/></View>}

function Trips({setFlow}:{setFlow:(f:Flow)=>void}){return <View style={s.stack}><Text style={s.sectionTitle}>Assigned trips</Text><DriverMap compact/><View style={s.card}><TripRow id="EN-001" route="Santo Domingo → Santiago" time="08:30" status="Boarding soon"/><TripRow id="EN-002" route="Santo Domingo → Punta Cana" time="11:15" status="Scheduled"/><TripRow id="EN-004" route="Santiago → La Vega" time="15:40" status="Scheduled"/></View><Primary label="Open boarding" icon="people-outline" onPress={()=>setFlow('boarding')}/></View>}
function Alerts({setFlow}:{setFlow:(f:Flow)=>void}){return <View style={s.stack}><View style={s.alertHero}><MaterialCommunityIcons name="radar" size={28} color={c.blue2}/><View><Text style={s.cardTitle}>Operations radar</Text><Text style={s.meta}>Live alerts, route conditions and vehicle status.</Text></View></View><View style={s.card}><Alert icon="time-outline" title="Boarding window" text="EN-001 boarding opens in 10 minutes."/><Alert icon="construct-outline" title="Vehicle" text="Bus 203 inspection is complete."/><Alert icon="cloud-outline" title="Route conditions" text="No major delays on Autopista Duarte."/><Alert icon="radio-outline" title="Operations" text="Control center is connected."/></View><Secondary label="Report an incident" icon="warning-outline" onPress={()=>setFlow('incident')}/></View>}
function Profile(){return <View style={s.stack}><View style={s.profile}><View style={s.profileAvatar}><Text style={s.profileAvatarText}>RL</Text></View><Text style={s.cardTitle}>Ricardo Luna</Text><Text style={s.meta}>Driver profile · Available</Text></View><View style={s.card}><Info label="Assigned vehicle" value={`${trip.vehicle} · ${trip.plate}`}/><Info label="License" value="DOP-D-5520"/><Info label="Shift" value="07:30 - 17:00"/><Info label="Operations" value="Connected"/><Info label="Safety score" value="98 / 100"/></View></View>}

function Telemetry({icon,label,value,hint}:{icon:keyof typeof MaterialCommunityIcons.glyphMap;label:string;value:string;hint:string}){return <View style={s.telemetryItem}><MaterialCommunityIcons name={icon} size={18} color={c.blue2}/><Text style={s.telemetryLabel}>{label}</Text><Text style={s.telemetryValue}>{value}</Text><Text style={s.telemetryHint}>{hint}</Text></View>}
function NavMetric({label,value}:{label:string;value:string}){return <View style={s.navMetric}><Text style={s.meta}>{label}</Text><Text style={s.navMetricValue}>{value}</Text></View>}
function Field({label,value,secure}:{label:string;value:string;secure?:boolean}){return <View style={s.field}><Text style={s.meta}>{label}</Text><TextInput secureTextEntry={secure} style={s.input} defaultValue={value}/></View>}
function Info({label,value}:{label:string;value:string}){return <View style={s.info}><Text style={s.meta}>{label}</Text><Text style={s.infoValue}>{value}</Text></View>}
function Metric({icon,label,value}:{icon:keyof typeof Ionicons.glyphMap;label:string;value:string}){return <View style={s.metric}><Ionicons name={icon} size={16} color="#a8e8ff"/><Text style={s.metricLabel}>{label}</Text><Text style={s.metricValue}>{value}</Text></View>}
function TripRow({id,route,time,status}:{id:string;route:string;time:string;status:string}){return <View style={s.tripRow}><View style={s.tripCode}><Text style={s.tripCodeText}>{id}</Text></View><View style={{flex:1}}><Text style={s.tripRoute}>{route}</Text><Text style={s.meta}>{time} · {status}</Text></View><Ionicons name="chevron-forward" size={20} color={c.muted}/></View>}
function Alert({icon,title,text}:{icon:keyof typeof Ionicons.glyphMap;title:string;text:string}){return <View style={s.alert}><View style={s.alertIcon}><Ionicons name={icon} size={18} color={c.blue2}/></View><View style={{flex:1}}><Text style={s.alertTitle}>{title}</Text><Text style={s.meta}>{text}</Text></View></View>}
function Primary({label,icon,onPress}:{label:string;icon?:keyof typeof Ionicons.glyphMap;onPress:()=>void}){return <Pressable onPress={onPress} style={({pressed})=>[s.primary,pressed&&{transform:[{scale:.985}]}]}>{icon&&<Ionicons name={icon} size={18} color={c.white}/>}<Text style={s.primaryText}>{label}</Text></Pressable>}
function Secondary({label,icon,onPress}:{label:string;icon?:keyof typeof Ionicons.glyphMap;onPress:()=>void}){return <Pressable onPress={onPress} style={s.secondary}>{icon&&<Ionicons name={icon} size={18} color={c.ink}/>}<Text style={s.secondaryText}>{label}</Text></Pressable>}
function BottomNav({tab,setTab}:{tab:Tab;setTab:(t:Tab)=>void}){const items:[Tab,keyof typeof Ionicons.glyphMap,string][]=[['home','home-outline','Home'],['trips','map-outline','Trips'],['alerts','notifications-outline','Alerts'],['profile','person-outline','Profile']];return <View style={s.nav}>{items.map(([t,icon,label])=><Pressable key={t} onPress={()=>setTab(t)} style={s.navItem}><Ionicons name={icon} size={20} color={tab===t?c.blue2:c.muted}/><Text style={[s.navText,tab===t&&{color:c.blue2,fontWeight:'900'}]}>{label}</Text></Pressable>)}</View>}

const s=StyleSheet.create({
safe:{flex:1,backgroundColor:c.bg},app:{flex:1},content:{padding:16,paddingBottom:110,gap:16},stack:{gap:16},
splashSafe:{flex:1,backgroundColor:c.ink},splash:{flex:1,padding:28,justifyContent:'center',gap:16},splashOrb:{width:76,height:76,borderRadius:28,backgroundColor:c.blue2,alignItems:'center',justifyContent:'center'},splashBrand:{fontSize:12,fontWeight:'900',color:'#8cdffc',letterSpacing:1.5},splashTitle:{fontSize:39,fontWeight:'900',color:c.white,letterSpacing:-1.4},splashCopy:{fontSize:14,lineHeight:21,color:'#b8c9d2'},
login:{flex:1,padding:24,justifyContent:'center',gap:14},loginIcon:{width:66,height:66,borderRadius:23,backgroundColor:c.ink,alignItems:'center',justifyContent:'center'},brand:{fontSize:10,fontWeight:'900',color:c.muted,letterSpacing:1.2,textTransform:'uppercase'},title:{fontSize:29,fontWeight:'900',color:c.ink,letterSpacing:-.8},field:{backgroundColor:c.white,borderWidth:1,borderColor:c.line,borderRadius:18,padding:13},input:{fontSize:15,fontWeight:'800',color:c.ink,paddingVertical:3},biometric:{flexDirection:'row',gap:10,alignItems:'center',backgroundColor:'#e8f7fb',borderRadius:18,padding:13},
header:{paddingHorizontal:16,paddingVertical:12,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},statusPill:{flexDirection:'row',gap:6,alignItems:'center',paddingHorizontal:10,paddingVertical:8,borderRadius:14,backgroundColor:'#edf2f4'},statusPillActive:{backgroundColor:'#e6f7ef'},statusDot:{width:7,height:7,borderRadius:4,backgroundColor:c.muted},statusDotActive:{backgroundColor:c.green},statusText:{fontSize:9,fontWeight:'900',color:c.ink},
command:{backgroundColor:c.ink,borderRadius:26,padding:18,gap:9},commandTop:{flexDirection:'row',justifyContent:'space-between'},commandLabel:{fontSize:9,fontWeight:'900',letterSpacing:.9,color:'#8cdffc'},readyBadge:{fontSize:8,fontWeight:'900',color:c.green,backgroundColor:'#e8f7ef',paddingHorizontal:9,paddingVertical:5,borderRadius:10},commandId:{fontSize:34,fontWeight:'900',color:c.white},commandRoute:{fontSize:19,fontWeight:'900',color:c.white},metricRow:{flexDirection:'row',gap:8,marginVertical:7},metric:{flex:1,backgroundColor:'#1a3344',borderRadius:16,padding:10},metricLabel:{fontSize:7,color:'#8ca3b0',marginTop:5},metricValue:{fontSize:11,fontWeight:'900',color:c.white,marginTop:2},
primary:{minHeight:52,borderRadius:17,backgroundColor:c.blue2,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:8,paddingHorizontal:16},primaryText:{color:c.white,fontSize:12,fontWeight:'900'},secondary:{minHeight:52,borderRadius:17,borderWidth:1,borderColor:c.line,backgroundColor:c.white,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:8,paddingHorizontal:16},secondaryText:{color:c.ink,fontSize:12,fontWeight:'900'},
map:{height:350,borderRadius:24,overflow:'hidden',borderWidth:1,borderColor:c.line},mapCompact:{height:220},busMarker:{width:34,height:34,borderRadius:17,backgroundColor:c.blue2,alignItems:'center',justifyContent:'center',borderWidth:3,borderColor:c.white},mapOverlay:{position:'absolute',left:12,right:12,bottom:12,backgroundColor:'rgba(255,255,255,.96)',borderRadius:17,padding:12,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},mapOverlayLabel:{fontSize:8,color:c.muted,fontWeight:'900'},mapOverlayValue:{fontSize:13,color:c.ink,fontWeight:'900'},mapStatus:{flexDirection:'row',gap:5,alignItems:'center'},mapStatusText:{fontSize:9,fontWeight:'900',color:c.green},liveDot:{width:7,height:7,borderRadius:4,backgroundColor:c.green},
telemetry:{flexDirection:'row',gap:8},telemetryItem:{flex:1,backgroundColor:c.white,borderWidth:1,borderColor:c.line,borderRadius:18,padding:10},telemetryLabel:{fontSize:7,color:c.muted,fontWeight:'800',marginTop:7},telemetryValue:{fontSize:11,fontWeight:'900',color:c.ink,marginTop:2},telemetryHint:{fontSize:7,color:c.green,marginTop:2},
opsCard:{backgroundColor:c.white,borderWidth:1,borderColor:c.line,borderRadius:22,padding:15},card:{backgroundColor:c.white,borderWidth:1,borderColor:c.line,borderRadius:22,padding:15},cardTitle:{fontSize:19,fontWeight:'900',color:c.ink},meta:{fontSize:10,color:c.muted},info:{paddingVertical:10,borderBottomWidth:1,borderBottomColor:'#e9eef1'},infoValue:{fontSize:13,fontWeight:'900',color:c.ink,marginTop:2},
boardSummary:{flexDirection:'row',gap:12,alignItems:'center',backgroundColor:'#e8f7fb',borderRadius:22,padding:15},boardCount:{width:65,height:65,borderRadius:22,backgroundColor:c.ink,alignItems:'center',justifyContent:'center'},boardCountText:{color:c.white,fontWeight:'900',fontSize:18},scanCard:{flexDirection:'row',gap:12,alignItems:'center',backgroundColor:c.white,borderWidth:1,borderColor:c.line,borderRadius:22,padding:14},scanIcon:{width:52,height:52,borderRadius:18,backgroundColor:'#e8f7fb',alignItems:'center',justifyContent:'center'},searchBox:{height:48,borderRadius:15,backgroundColor:'#f3f7f9',flexDirection:'row',alignItems:'center',gap:8,paddingHorizontal:12,marginBottom:9},search:{flex:1;color:c.ink},passengerRow:{flexDirection:'row',alignItems:'center',gap:10,paddingVertical:10,borderBottomWidth:1,borderBottomColor:'#edf1f3'},passengerAvatar:{width:40,height:40,borderRadius:14,backgroundColor:'#e8f7fb',alignItems:'center',justifyContent:'center'},passengerAvatarText:{fontSize:9,fontWeight:'900',color:c.blue2},passengerName:{fontSize:13,fontWeight:'900',color:c.ink},passengerStatus:{fontSize:9,fontWeight:'900'},boarded:{color:c.green},absent:{color:c.red},pending:{color:c.amber},
liveCommand:{backgroundColor:c.white,borderWidth:1,borderColor:c.line,borderRadius:22,padding:15,gap:8},liveTop:{flexDirection:'row',justifyContent:'space-between'},live:{flexDirection:'row',gap:5,alignItems:'center',backgroundColor:'#e8f7ef',paddingHorizontal:9,paddingVertical:7,borderRadius:12},liveText:{fontSize:8,fontWeight:'900',color:c.green},navMetrics:{flexDirection:'row',gap:8,marginVertical:8},navMetric:{flex:1,backgroundColor:'#f2f7f9',borderRadius:16,padding:10},navMetricValue:{fontSize:14,fontWeight:'900',color:c.ink},actionRow:{flexDirection:'row',gap:8,marginTop:8},actionRow:{flexDirection:'row',gap:8,marginTop:8},
incidentGrid:{flexDirection:'row',flexWrap:'wrap',gap:8,marginVertical:10},incidentType:{width:'48%',minHeight:70,borderRadius:18,borderWidth:1,borderColor:c.line,backgroundColor:'#f8fafb',alignItems:'center',justifyContent:'center',gap:5},incidentActive:{backgroundColor:c.blue2,borderColor:c.blue2},incidentText:{fontSize:10,fontWeight:'900',color:c.ink},incidentTextActive:{color:c.white},notes:{minHeight:120,borderRadius:16,borderWidth:1,borderColor:c.line,padding:12,textAlignVertical:'top',color:c.ink},
complete:{backgroundColor:c.white,borderWidth:1,borderColor:c.line,borderRadius:24,padding:24,alignItems:'center',gap:12},completeHalo:{width:70,height:70,borderRadius:35,backgroundColor:c.green,alignItems:'center',justifyContent:'center'},metaCenter:{fontSize:11,color:c.muted,textAlign:'center'},completeSummary:{width:'100%'},
sectionTitle:{fontSize:22,fontWeight:'900',color:c.ink},tripRow:{flexDirection:'row',alignItems:'center',gap:10,paddingVertical:12,borderBottomWidth:1,borderBottomColor:'#edf1f3'},tripCode:{paddingHorizontal:9,paddingVertical:7,borderRadius:10,backgroundColor:'#e8f7fb'},tripCodeText:{fontSize:8,fontWeight:'900',color:c.blue2},tripRoute:{fontSize:12,fontWeight:'900',color:c.ink},
alertHero:{flexDirection:'row',gap:12,alignItems:'center',backgroundColor:'#e8f7fb',borderRadius:22,padding:15},alert:{flexDirection:'row',gap:10,paddingVertical:12,borderBottomWidth:1,borderBottomColor:'#edf1f3'},alertIcon:{width:38,height:38,borderRadius:13,backgroundColor:'#eef8fb',alignItems:'center',justifyContent:'center'},alertTitle:{fontSize:12,fontWeight:'900',color:c.ink},
profile:{alignItems:'center',backgroundColor:c.white,borderWidth:1,borderColor:c.line,borderRadius:24,padding:22},profileAvatar:{width:78,height:78,borderRadius:26,backgroundColor:c.ink,alignItems:'center',justifyContent:'center',marginBottom:10},profileAvatarText:{fontSize:23,fontWeight:'900',color:c.white},
navSafe:{backgroundColor:c.bg},nav:{marginHorizontal:12,marginBottom:6,borderRadius:24,backgroundColor:c.white,borderWidth:1,borderColor:c.line,flexDirection:'row'},navItem:{flex:1,minHeight:58,alignItems:'center',justifyContent:'center',gap:3},navText:{fontSize:8,color:c.muted}
});
