import { login, logout, fetchAdminDashboard, fetchAdminReport, getApiToken } from '../../packages/shared/api.mjs';
import { formatCurrency, formatDateLabel, formatTimeLabel } from '../../packages/shared/domain.mjs';
import { statCard } from '../../packages/shared/ui.mjs';
const appRoot=document.querySelector('#app'); const state={screen:getApiToken()?'loading':'login',loading:false,activeModule:'dashboard',search:'',dashboard:null,report:null,error:''};
const modules=[['dashboard','Dashboard'],['trips','Trips'],['buses','Buses'],['drivers','Drivers'],['bookings','Bookings'],['reports','Reports']];
function esc(v=''){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function render(){if(state.screen==='login'){appRoot.innerHTML=`<div class="admin-layout"><section class="admin-main"><div class="admin-panel admin-panel--pad" style="max-width:560px;margin:8vh auto"><div class="admin-brand"><img class="admin-brand__logo" src="/logo.svg" alt="Encore Transport"><div><strong>Encore Control</strong><small>Administrator authentication</small></div></div><h1 class="page-title">Operations access</h1>${state.error?`<div class="feed-item"><strong>Login error</strong><div>${esc(state.error)}</div></div>`:''}<form id="adminLogin" class="grid"><input class="field" name="email" type="email" placeholder="Email" required><input class="field" name="password" type="password" placeholder="Password" required><button class="button button--primary">Sign in</button></form></div></section></div>`;wire();return}if(state.screen==='loading'){appRoot.innerHTML='<div class="admin-layout"><section class="admin-main"><div class="admin-panel admin-panel--pad"><h2>Loading real operational data…</h2></div></section></div>';return}const d=normalize(state.dashboard);appRoot.innerHTML=`<div class="admin-layout motion-enter"><aside class="admin-sidebar"><div class="admin-brand"><img class="admin-brand__logo" src="/logo.svg" alt="Encore Transport"><div><strong>Encore Control</strong><small>Admin Dashboard</small></div></div><nav class="admin-nav">${modules.map(([id,label])=>`<div class="admin-nav__item ${id===state.activeModule?'admin-nav__item--active':''}" data-module="${id}">${label}</div>`).join('')}</nav></aside><section class="admin-main"><header class="admin-topbar"><div><div class="eyebrow">Centralized operations</div><h1 class="page-title">${modules.find(x=>x[0]===state.activeModule)?.[1]}</h1></div><div class="admin-controls"><input class="field" id="searchInput" placeholder="Search..." value="${esc(state.search)}"><button class="button button--ghost" id="refresh">Refresh</button><button class="button button--ghost" id="logout">Logout</button></div></header>${state.error?`<div class="admin-panel admin-panel--pad"><strong>API error</strong><p>${esc(state.error)}</p></div>`:''}${content(d)}</section></div>`;wire()}
function content(d){if(state.activeModule==='dashboard')return `<section class="admin-stats">${statCard("Today's trips",d.metrics.tripsToday,'Database')}${statCard('Bookings',d.metrics.bookings,'Database')}${statCard('Revenue',formatCurrency(d.metrics.revenue),'Confirmed bookings')}${statCard('Passengers',d.metrics.passengers,'Registered')}</section>${table('Trips',d.trips.map(t=>[t.routeName,t.departureTime,t.bus,t.driver,t.status]),['Route','Departure','Bus','Driver','Status'])}`;if(state.activeModule==='trips')return table('Trips',filter(d.trips).map(t=>[t.routeName,t.date,t.departureTime,t.availableSeats,t.status]),['Route','Date','Departure','Available','Status']);if(state.activeModule==='buses')return table('Buses',filter(d.buses).map(x=>[x.code,x.plate,x.capacity,x.status]),['Code','Plate','Capacity','Status']);if(state.activeModule==='drivers')return table('Drivers',filter(d.drivers).map(x=>[x.name,x.license_number,x.status]),['Name','License','Status']);if(state.activeModule==='bookings')return table('Bookings',filter(d.bookings).map(x=>[x.reference,x.passenger_name,x.status,x.total_amount]),['Reference','Passenger','Status','Total']);if(state.activeModule==='reports'){const r=state.report;return `<section class="admin-panel admin-panel--pad"><div class="module-view__header"><div><div class="eyebrow">Reports</div><h2>Real period report</h2></div><button id="loadReport" class="button button--primary">Last 7 days</button></div>${r?`<div class="grid grid--3">${statCard('Trips',r.trips.total,'Period')}${statCard('Bookings',r.bookings.total,'Period')}${statCard('Paid payments',r.payments.paid,'Period')}${statCard('Incidents',r.incidents,'Period')}</div>`:'<p>Select a period report.</p>'}</section>`}return ''}
function table(title,rows,headers){return `<section class="admin-panel admin-panel--pad module-view"><div class="module-view__header"><div><div class="eyebrow">${title}</div><h2>${title}</h2></div><span class="badge badge--neutral">${rows.length} records</span></div><div class="table-wrap"><table class="table admin-table"><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${esc(c)}</td>`).join('')}</tr>`).join('')}</tbody></table></div></section>`}
function normalize(x){return{metrics:{tripsToday:x?.metrics?.tripsToday??0,bookings:x?.metrics?.bookings??0,passengers:x?.metrics?.passengers??0,revenue:x?.metrics?.revenue??0},trips:(x?.trips??[]).map(t=>({id:t.id,routeName:t.routeName??`${t.route?.origin??''} → ${t.route?.destination??''}`,date:t.date??t.departure_date??'',departureTime:t.departureTime??t.departure_time??'',availableSeats:t.availableSeats??t.available_seats??0,bus:t.busCode??t.bus?.code??'',driver:t.driverName??t.driver?.name??'',status:t.status??''})),buses:x?.buses??[],drivers:x?.drivers??[],bookings:x?.bookings??[]}}
function filter(rows){const q=state.search.trim().toLowerCase();return q?rows.filter(r=>Object.values(r).some(v=>String(v??'').toLowerCase().includes(q))):rows}
async function load(){state.screen='loading';render();try{state.dashboard=await fetchAdminDashboard();state.error='';state.screen='dashboard'}catch(e){state.error=e.message;if(e.status===401||e.status===403){localStorage.removeItem('encore_api_token');state.screen='login'}else state.screen='dashboard'}render()}
function wire(){document.querySelector('#adminLogin')?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await login(String(f.get('email')),String(f.get('password')));await load()}catch(err){state.error=err.message;render()}});document.querySelector('#logout')?.addEventListener('click',async()=>{await logout();state.screen='login';state.dashboard=null;render()});document.querySelector('#refresh')?.addEventListener('click',load);document.querySelector('#searchInput')?.addEventListener('input',e=>{state.search=e.target.value;render()});document.querySelectorAll('[data-module]').forEach(x=>x.addEventListener('click',()=>{state.activeModule=x.dataset.module;render()}));document.querySelector('#loadReport')?.addEventListener('click',async()=>{try{state.report=await fetchAdminReport();state.error='';render()}catch(e){state.error=e.message;render()}})}
if(getApiToken())load();else render();
