import { getApiToken, me, logout } from '../../packages/shared/api.mjs';
import { modules } from './src/module-registry.mjs';
import * as api from './src/api.mjs';
import { dashboardView, table, reportView } from './src/views.mjs';
const root=document.querySelector('#app');
const state={module:'dashboard',loading:true,error:'',dashboard:null,incidents:[],schedules:[],packages:[],vehicleStatus:[],reportType:'executive',reportData:null,user:null};
function redirectLogin(){location.replace('/login/?return='+encodeURIComponent('/admin/'));}
async function ensureAdmin(){if(!getApiToken())return redirectLogin();try{const p=await me();state.user=p.user??p.data?.user??p;if(state.user?.role!=='admin'){state.error='This account does not have access to Operations.';return false}return true}catch{return redirectLogin()}}
function sidebar(){let last='';return `<aside class="admin-sidebar"><div class="admin-brand"><img class="admin-brand__logo" src="/logo.svg" alt="Encore Transport"><div><strong>Encore Control</strong><small>Operations Center</small></div></div><nav class="admin-nav">${modules.map(m=>{const group=m.group!==last?`<div class="eyebrow" style="margin:16px 12px 6px">${m.group}</div>`:'';last=m.group;return `${group}<button class="admin-nav__item ${state.module===m.id?'admin-nav__item--active':''}" data-module="${m.id}">${m.label}</button>`}).join('')}</nav></aside>`}
function content(){if(state.loading)return '<section class="admin-panel admin-panel--pad"><h2>Loading…</h2></section>';if(state.error)return `<section class="admin-panel admin-panel--pad"><h2>Unable to load this area</h2><p>${state.error}</p><button class="button button--primary" id="retry">Retry</button></section>`;const d=state.dashboard??{};if(state.module==='dashboard')return dashboardView(d);if(state.module==='trips')return table('Trips',['Route','Date','Departure','Bus','Driver','Status'],(d.trips??[]).map(t=>[t.route?.origin&&t.route?.destination?`${t.route.origin} → ${t.route.destination}`:'—',String(t.departure_date??'').slice(0,10),t.departure_time,t.bus?.code,t.driver?.name,t.status]));if(state.module==='bookings')return table('Bookings',['Reference','Passenger','Status','Total'],(d.bookings??[]).map(b=>[b.reference,b.passenger_name,b.status,b.total_amount]));if(state.module==='vehicles')return table('Vehicles',['Code','Plate','Capacity','Status'],(d.buses??[]).map(b=>[b.code,b.plate,b.capacity,b.status]));if(state.module==='drivers')return table('Drivers',['Name','License','Status'],(d.drivers??[]).map(x=>[x.name,x.license_number,x.status]));if(state.module==='routes')return table('Routes',['Origin','Destination','Distance','Active'],(d.routes??[]).map(x=>[x.origin,x.destination,x.distance_km?`${x.distance_km} km`:'—',x.active?'Yes':'No']));if(state.module==='incidents')return table('Incidents',['Trip','Title','Severity','Status','Created'],state.incidents.map(x=>[x.trip?.id,x.title,x.severity,x.status,x.created_at]));if(state.module==='schedules')return table('Driver schedules',['Date','Driver','Vehicle','Start','End','Status'],state.schedules.map(x=>[String(x.work_date??'').slice(0,10),x.driver?.name,x.bus?.code,x.starts_at,x.ends_at,x.status]));if(state.module==='packages')return table('Packages',['Reference','Route','Recipient','Status','Created'],state.packages.map(x=>[x.reference,x.trip?.route?`${x.trip.route.origin} → ${x.trip.route.destination}`:'—',x.recipient_name,x.status,x.created_at]));if(state.module==='reports')return `<section class="admin-panel admin-panel--pad"><div class="module-view__header"><div><div class="eyebrow">Reports</div><h2>Choose a business question</h2></div><select id="reportType" class="select"><option value="executive" ${state.reportType==='executive'?'selected':''}>Executive dashboard</option><option value="travel" ${state.reportType==='travel'?'selected':''}>Travel Report</option><option value="vehicles" ${state.reportType==='vehicles'?'selected':''}>Vehicle Report</option><option value="trips" ${state.reportType==='trips'?'selected':''}>Trip Report</option><option value="trip-costs" ${state.reportType==='trip-costs'?'selected':''}>Trip Cost Summary</option></select></div></section>${state.reportData?reportView(state.reportType,state.reportData):''}`;return ''}
function render(){root.innerHTML=`<div class="admin-layout motion-enter">${sidebar()}<section class="admin-main"><header class="admin-topbar"><div><div class="eyebrow">Centralized operations</div><h1 class="page-title">${modules.find(m=>m.id===state.module)?.label??'Operations'}</h1></div><div class="admin-controls"><span>${state.user?.name??''}</span><button class="button button--ghost" id="refresh">Refresh</button><button class="button button--ghost" id="logout">Logout</button></div></header>${content()}</section></div>`;wire()}
async function loadModule(){state.loading=true;state.error='';render();try{if(!state.dashboard)state.dashboard=await api.dashboard();if(state.module==='incidents')state.incidents=await api.incidents();if(state.module==='schedules')state.schedules=await api.schedules();if(state.module==='packages')state.packages=await api.packages();if(state.module==='vehicles')state.vehicleStatus=await api.vehicleStatus();if(state.module==='reports')state.reportData=await api.report(state.reportType);state.loading=false}catch(e){state.loading=false;state.error=e.message}render()}
function wire(){document.querySelectorAll('[data-module]').forEach(b=>b.addEventListener('click',()=>{state.module=b.dataset.module;state.reportData=null;void loadModule()}));document.querySelector('#refresh')?.addEventListener('click',()=>{state.dashboard=null;void loadModule()});document.querySelector('#retry')?.addEventListener('click',loadModule);document.querySelector('#logout')?.addEventListener('click',async()=>{await logout();redirectLogin()});document.querySelector('#reportType')?.addEventListener('change',e=>{state.reportType=e.target.value;state.reportData=null;void loadModule()})}
if(await ensureAdmin())await loadModule();else render();
