import { FormEvent, useEffect, useMemo, useState } from 'react';
import { SeatMap, type SeatDto } from './seat-map';

type Screen='home'|'results'|'trip'|'seats'|'passengers'|'review'|'status';
type ApiTrip={id:number|string;origin:string;destination:string;date:string;departureTime:string;arrivalTime:string;durationMinutes:number;baseFare:number;busId?:string;busCode?:string;driverName?:string;status:string;availableSeats:number};
type Passenger={full_name:string;document_number:string;email:string;phone:string};
type Booking={id:number;reference?:string;status:string;total_amount?:number;expires_at?:string;seat_numbers?:string[]};
type Quote={currency:string;base_fare:number;passengers:number;fees:number;discounts:number;taxes:number;subtotal:number;total:number};
const API='/api/v1';const TOKEN='encore_api_token';const DRAFT='encore_booking_draft';const money=(v:number,currency='DOP')=>new Intl.NumberFormat('en-US',{style:'currency',currency,maximumFractionDigits:0}).format(Number(v||0));
async function api(path:string,opts:RequestInit={}){const token=sessionStorage.getItem(TOKEN)??localStorage.getItem(TOKEN);const headers=new Headers(opts.headers);headers.set('Accept','application/json');if(opts.body)headers.set('Content-Type','application/json');if(token)headers.set('Authorization',`Bearer ${token}`);const r=await fetch(`${API}${path}`,{...opts,headers});const p=await r.json().catch(()=>({}));if(!r.ok){const detail=p.errors?Object.values(p.errors).flat().join(' '):p.message;const e=new Error(String(detail||`Request failed (${r.status})`));(e as any).status=r.status;throw e;}return p;}
function initialFilters(){const q=new URLSearchParams(location.search);return{origin:q.get('origin')??'',destination:q.get('destination')??'',date:q.get('date')??'',passengers:Math.max(1,Number(q.get('passengers')??1)||1)}}
export function PassengerApp(){
 const[start]=useState(initialFilters);const[screen,setScreen]=useState<Screen>('home');const[history,setHistory]=useState<Screen[]>([]);const[filters,setFilters]=useState(start);const[trips,setTrips]=useState<ApiTrip[]>([]);const[selectedTrip,setSelectedTrip]=useState<ApiTrip|null>(null);const[seats,setSeats]=useState<SeatDto[]>([]);const[selected,setSelected]=useState<number[]>([]);const[passengers,setPassengers]=useState<Passenger[]>(()=>Array.from({length:start.passengers},()=>({full_name:'',document_number:'',email:'',phone:''})));const[booking,setBooking]=useState<Booking|null>(null);const[quote,setQuote]=useState<Quote|null>(null);const[loading,setLoading]=useState(false);const[error,setError]=useState('');
 const go=(next:Screen)=>{setHistory(h=>[...h,screen]);setScreen(next);scrollTo({top:0,behavior:'smooth'})};const back=()=>setHistory(h=>{const n=[...h];const p=n.pop();if(p)setScreen(p);return n});
 const search=async(next=filters)=>{setLoading(true);setError('');try{const q=new URLSearchParams();if(next.origin)q.set('origin',next.origin);if(next.destination)q.set('destination',next.destination);if(next.date)q.set('date',next.date);q.set('passengers',String(next.passengers));const p=await api(`/trips/search?${q}`);setTrips(p.data??[]);setPassengers(Array.from({length:next.passengers},(_,i)=>passengers[i]??{full_name:'',document_number:'',email:'',phone:''}));if(screen!=='results')go('results')}catch(e){setError((e as Error).message);setTrips([]);if(screen!=='results')go('results')}finally{setLoading(false)}};
 const choose=async(t:ApiTrip)=>{setLoading(true);setError('');try{const[detail,seatPayload,quotePayload]=await Promise.all([api(`/trips/${t.id}`),api(`/trips/${t.id}/seats`),api(`/trips/${t.id}/quote?passengers=${filters.passengers}`)]);setSelectedTrip(detail.data??detail);setSeats(seatPayload.data??[]);setQuote(quotePayload.data??quotePayload);setSelected([]);go('trip')}catch(e){setError((e as Error).message)}finally{setLoading(false)}};
 const toggle=(id:number)=>setSelected(s=>s.includes(id)?s.filter(x=>x!==id):s.length<filters.passengers?[...s,id]:s);
 const reserve=async()=>{if(!selectedTrip)return;if(!sessionStorage.getItem(TOKEN)&&!localStorage.getItem(TOKEN)){sessionStorage.setItem(DRAFT,JSON.stringify({filters,tripId:selectedTrip.id,selected,passengers}));location.href='/login/?return='+encodeURIComponent('/passenger/?resume=1');return;}setLoading(true);setError('');try{const p=await api('/bookings',{method:'POST',body:JSON.stringify({trip_id:Number(selectedTrip.id),seat_ids:selected,passengers})});setBooking(p.data??p);sessionStorage.removeItem(DRAFT);go('status')}catch(e){setError((e as Error).message)}finally{setLoading(false)}};
 useEffect(()=>{const q=new URLSearchParams(location.search);if(q.get('resume')==='1'){const raw=sessionStorage.getItem(DRAFT);if(raw){void(async()=>{try{const d=JSON.parse(raw);setFilters(d.filters);setPassengers(d.passengers);const[tripPayload,seatPayload,quotePayload]=await Promise.all([api(`/trips/${d.tripId}`),api(`/trips/${d.tripId}/seats`),api(`/trips/${d.tripId}/quote?passengers=${d.filters.passengers}`)]);setSelectedTrip(tripPayload.data??tripPayload);setSeats(seatPayload.data??[]);setQuote(quotePayload.data??quotePayload);setSelected(d.selected);setScreen('review')}catch(e){setError((e as Error).message)}})();return;}}if(start.origin||start.destination)void search(start)},[]);
 const selectedLabels=useMemo(()=>seats.filter(s=>selected.includes(s.id)).map(s=>s.seat_number),[seats,selected]);const step=['home','results','trip','seats','passengers','review','status'].indexOf(screen);
 return <div className="app-shell"><Topbar/><div className="passenger-wrap"><Journey step={step}/>{error&&<div className="smart-banner"><b>Could not complete the action</b><span>{error}</span></div>}<main className="screen-animate">{screen==='home'&&<Home filters={filters} setFilters={setFilters} onSearch={()=>search(filters)} loading={loading}/>} {screen==='results'&&<Results trips={trips} loading={loading} onBack={back} onSelect={choose}/>} {screen==='trip'&&selectedTrip&&<TripScreen trip={selectedTrip} onBack={back} onNext={()=>go('seats')}/>} {screen==='seats'&&<SeatScreen seats={seats} selected={selected} passengerCount={filters.passengers} toggle={toggle} onBack={back} onNext={()=>go('passengers')}/>} {screen==='passengers'&&<Passengers values={passengers} setValues={setPassengers} onBack={back} onNext={()=>go('review')}/>} {screen==='review'&&selectedTrip&&<Review trip={selectedTrip} seatLabels={selectedLabels} passengers={passengers} quote={quote} loading={loading} onBack={back} onReserve={reserve}/>} {screen==='status'&&<Status booking={booking} trip={selectedTrip} seats={selectedLabels} onNew={()=>{setBooking(null);setSelected([]);setScreen('home')}}/>}</main></div></div>
}
function Topbar(){return <header className="topbar"><div className="brand"><img src="/logo.svg" alt="Encore Transport"/><div><strong>Encore Passenger</strong><span>Book, board and travel</span></div></div><nav><button onClick={()=>location.href='/website/'}>Website</button><button onClick={()=>location.href='/login/'}>Account</button></nav><div className="user"><span>Passenger</span><b>ET</b></div></header>}
function Journey({step}:{step:number}){const labels=['Search','Results','Trip','Seats','Passengers','Review','Status'];const pct=Math.max(0,Math.round(step/(labels.length-1)*100));return <section className="journey"><div className="journey-top"><span>BOOKING JOURNEY</span><strong>{pct}%</strong></div><div className="journey-bar"><i style={{width:`${pct}%`}}/></div><div className="journey-steps">{labels.map((x,i)=><button key={x} disabled className={i<=step?'active':''}><em>{String(i+1).padStart(2,'0')}</em>{x}</button>)}</div></section>}
function Home({filters,setFilters,onSearch,loading}:{filters:any;setFilters:(x:any)=>void;onSearch:()=>void;loading:boolean}){const submit=(e:FormEvent)=>{e.preventDefault();onSearch()};return <><section className="hero"><div><span className="eyebrow">INTERCITY, REFINED</span><h1>Move through the island with context.</h1><p>Search current departures, inspect the assigned vehicle and choose actual available seats.</p></div><div className="orbit"><i></i><b>ENCORE</b><span>FROM</span><span>TO</span></div></section><form className="search-console" onSubmit={submit}><Field label="From" value={filters.origin} onChange={v=>setFilters({...filters,origin:v})}/><button type="button" onClick={()=>setFilters({...filters,origin:filters.destination,destination:filters.origin})}>⇄</button><Field label="To" value={filters.destination} onChange={v=>setFilters({...filters,destination:v})}/><Field label="Date" value={filters.date} type="date" onChange={v=>setFilters({...filters,date:v})}/><Field label="Passengers" value={String(filters.passengers)} type="number" onChange={v=>setFilters({...filters,passengers:Math.max(1,Number(v)||1)})}/><button className="primary" disabled={loading}>{loading?'SEARCHING…':'SEARCH DEPARTURES →'}</button></form></>}
function Field({label,value,type='text',onChange}:{label:string;value:string;type?:string;onChange?:(v:string)=>void}){return <label><span>{label}</span><input type={type} value={value} onChange={e=>onChange?.(e.target.value)}/></label>}
function PageHead({eyebrow,title,onBack}:{eyebrow:string;title:string;onBack:()=>void}){return <div className="page-head"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1></div><button className="ghost" onClick={onBack}>← BACK</button></div>}
function Results({trips,loading,onBack,onSelect}:{trips:ApiTrip[];loading:boolean;onBack:()=>void;onSelect:(t:ApiTrip)=>void}){return <><PageHead eyebrow="AVAILABLE DEPARTURES" title="Choose your departure." onBack={onBack}/>{loading?<div className="smart-banner"><b>Searching trips…</b></div>:!trips.length?<div className="smart-banner"><b>No departures found.</b><span>Change route, date or passenger count.</span></div>:<div className="departures">{trips.map(t=><article key={t.id} className="departure"><div><span>TRIP {t.id}</span><h3>{t.origin} → {t.destination}</h3><div className="times"><b>{t.departureTime?.slice(0,5)}</b><i></i><small>{t.durationMinutes} min</small><i></i><b>{t.arrivalTime?.slice(0,5)}</b></div><p>{t.busCode??`Bus ${t.busId??''}`} · {t.availableSeats} seats available · {t.status}</p></div><aside><strong>{money(t.baseFare)}</strong><button className="primary" onClick={()=>onSelect(t)}>SELECT →</button></aside></article>)}</div>}</>}
function TripScreen({trip,onBack,onNext}:{trip:ApiTrip;onBack:()=>void;onNext:()=>void}){return <><PageHead eyebrow={`TRIP ${trip.id}`} title={`${trip.origin} to ${trip.destination}`} onBack={onBack}/><div className="facts"><Fact label="Departure" value={`${trip.date} · ${trip.departureTime?.slice(0,5)}`}/><Fact label="Vehicle" value={trip.busCode??`Bus ${trip.busId??''}`}/><Fact label="Driver" value={trip.driverName??'Assigned by operations'}/><Fact label="Status" value={trip.status}/></div><div className="action-band"><div><span>FARE PER PASSENGER</span><strong>{money(trip.baseFare)}</strong></div><button className="primary" onClick={onNext}>CHOOSE SEATS →</button></div></>}
function Fact({label,value}:{label:string;value:string}){return <article><span>{label}</span><strong>{value}</strong></article>}
function SeatScreen({seats,selected,passengerCount,toggle,onBack,onNext}:{seats:SeatDto[];selected:number[];passengerCount:number;toggle:(n:number)=>void;onBack:()=>void;onNext:()=>void}){return <><PageHead eyebrow="CABIN SELECTION" title="Choose your place on board." onBack={onBack}/><div className="seat-layout"><SeatMap seats={seats} selected={selected} maxSelection={passengerCount} onToggle={toggle}/><aside className="seat-summary"><span className="eyebrow">YOUR SELECTION</span><h2>{selected.length}/{passengerCount} seats</h2><div className="seat-tags">{seats.filter(s=>selected.includes(s.id)).map(s=><b key={s.id}>{s.seat_number}</b>)}</div><p>Availability is validated again by the server when the booking is created.</p><button className="primary" disabled={selected.length!==passengerCount} onClick={onNext}>CONTINUE →</button></aside></div></>}
function Passengers({values,setValues,onBack,onNext}:{values:Passenger[];setValues:(x:Passenger[])=>void;onBack:()=>void;onNext:()=>void}){const update=(i:number,k:keyof Passenger,v:string)=>setValues(values.map((p,n)=>n===i?{...p,[k]:v}:p));const valid=values.every(p=>p.full_name.trim());return <><PageHead eyebrow="PASSENGER DETAILS" title="Who is travelling?" onBack={onBack}/><form className="passenger-form" onSubmit={e=>{e.preventDefault();if(valid)onNext()}}>{values.map((p,i)=><article className="passenger-card" key={i}><div className="passenger-no">{String(i+1).padStart(2,'0')}</div><div className="fields"><Field label="Full name" value={p.full_name} onChange={v=>update(i,'full_name',v)}/><Field label="Document" value={p.document_number} onChange={v=>update(i,'document_number',v)}/><Field label="Phone" value={p.phone} onChange={v=>update(i,'phone',v)}/><Field label="Email" value={p.email} type="email" onChange={v=>update(i,'email',v)}/></div></article>)}<button className="primary wide" disabled={!valid}>REVIEW TRIP →</button></form></>}
function Review({trip,seatLabels,passengers,quote,loading,onBack,onReserve}:{trip:ApiTrip;seatLabels:string[];passengers:Passenger[];quote:Quote|null;loading:boolean;onBack:()=>void;onReserve:()=>void}){const signed=!!(sessionStorage.getItem(TOKEN)??localStorage.getItem(TOKEN));return <><PageHead eyebrow="REVIEW" title="Everything in one clear view." onBack={onBack}/><div className="review-grid"><div className="review-card"><Fact label="Route" value={`${trip.origin} → ${trip.destination}`}/><Fact label="Passengers" value={passengers.map(p=>p.full_name).join(' · ')}/><Fact label="Seats" value={seatLabels.join(', ')}/><Fact label="Vehicle" value={trip.busCode??`Bus ${trip.busId??''}`}/>{!signed&&<div className="smart-banner"><b>Sign in required</b><span>Your booking selections will be preserved while you sign in.</span></div>}</div><aside className="total-panel"><span>SERVER TOTAL</span><strong>{money(quote?.total??0,quote?.currency??'DOP')}</strong><small>Calculated and validated by Encore before the reservation is created.</small><button className="primary" disabled={loading} onClick={onReserve}>{loading?'RESERVING…':signed?'HOLD SEATS / CREATE BOOKING →':'SIGN IN AND CONTINUE →'}</button></aside></div></>}
function Status({booking,trip,seats,onNew}:{booking:Booking|null;trip:ApiTrip|null;seats:string[];onNew:()=>void}){return <><div className="confirmation"><div>✓</div><h2>{booking?.status==='pending_payment'?'Your seats are being held.':'Booking status updated.'}</h2><p>No payment success is simulated. A final ticket is issued only after a configured provider verifies payment.</p></div><div className="facts"><Fact label="Booking" value={booking?.reference??String(booking?.id??'')}/><Fact label="Route" value={trip?`${trip.origin} → ${trip.destination}`:''}/><Fact label="Seats" value={seats.join(', ')}/><Fact label="Status" value={booking?.status??'unknown'}/></div><div className="action-band"><div><span>SERVER TOTAL</span><strong>{money(Number(booking?.total_amount??0))}</strong></div><button className="primary" onClick={onNew}>NEW SEARCH</button></div></>}
