import { FormEvent, useState } from 'react';

type Screen='home'|'results'|'trip'|'seats'|'passengers'|'review'|'payment'|'confirmation'|'ticket';
type Trip={id:string;origin:string;destination:string;departure:string;arrival:string;duration:string;price:number;bus:string;seats:number;featured?:boolean};
const trips:Trip[]=[
{id:'EN-001',origin:'Santo Domingo',destination:'Santiago',departure:'08:30',arrival:'10:45',duration:'2h 15m',price:685,bus:'Bus 203',seats:18,featured:true},
{id:'EN-014',origin:'Santo Domingo',destination:'Santiago',departure:'11:15',arrival:'13:35',duration:'2h 20m',price:735,bus:'Bus 118',seats:12},
{id:'EN-022',origin:'Santo Domingo',destination:'Santiago',departure:'15:10',arrival:'17:20',duration:'2h 10m',price:790,bus:'Bus 311',seats:9}
];
const flow:Screen[]=['home','results','trip','seats','passengers','review','payment','confirmation','ticket'];
const money=(v:number)=>`DOP ${v.toLocaleString('en-US')}`;

export function PassengerApp(){
 const[screen,setScreen]=useState<Screen>('home');const[history,setHistory]=useState<Screen[]>([]);
 const[selectedTrip,setSelectedTrip]=useState(trips[0]);const[selectedSeats,setSelectedSeats]=useState<string[]>(['4B','4C']);const[payment,setPayment]=useState('Card');const[verify,setVerify]=useState<'ready'|'checking'|'approved'>('ready');
 const step=flow.indexOf(screen);
 const go=(next:Screen)=>{setHistory(h=>[...h,screen]);setScreen(next);window.scrollTo({top:0,behavior:'smooth'})};
 const back=()=>setHistory(h=>{const n=[...h];const p=n.pop();if(p)setScreen(p);return n});
 const jump=(i:number)=>{if(i<step){setScreen(flow[i]);window.scrollTo({top:0,behavior:'smooth'})}};
 const toggle=(id:string)=>setSelectedSeats(s=>s.includes(id)?s.filter(x=>x!==id):s.length<2?[...s,id]:s);
 return <div className="app-shell">
   <Topbar/>
   <div className="passenger-wrap"><Journey step={step} jump={jump}/>
   <main className="screen-animate">
    {screen==='home'&&<Home onSearch={()=>go('results')}/>}
    {screen==='results'&&<Results onBack={back} onSelect={t=>{setSelectedTrip(t);go('trip')}}/>}
    {screen==='trip'&&<TripScreen trip={selectedTrip} onBack={back} onNext={()=>go('seats')}/>}
    {screen==='seats'&&<SeatScreen selected={selectedSeats} toggle={toggle} onBack={back} onNext={()=>go('passengers')}/>}
    {screen==='passengers'&&<Passengers onBack={back} onNext={()=>go('review')}/>}
    {screen==='review'&&<Review trip={selectedTrip} seats={selectedSeats} onBack={back} onNext={()=>go('payment')}/>}
    {screen==='payment'&&<Payment method={payment} setMethod={setPayment} state={verify} setState={setVerify} onBack={back} onNext={()=>go('confirmation')}/>}
    {screen==='confirmation'&&<Confirmation onBack={back} onTicket={()=>go('ticket')}/>}
    {screen==='ticket'&&<Ticket seats={selectedSeats} onBack={back}/>}
   </main></div>
 </div>
}
function Topbar(){return <header className="topbar"><div className="brand"><img src="/logo.svg"/><div><strong>Encore Passenger</strong><span>Book, board and travel</span></div></div><nav><button>Book</button><button>Trips</button><button>Support</button></nav><div className="user"><span>Maria Torres</span><b>MT</b></div></header>}
function Journey({step,jump}:{step:number;jump:(i:number)=>void}){const labels=['Search','Results','Trip','Seats','Passengers','Review','Pay','Ticket'];return <section className="journey"><div className="journey-top"><span>BOOKING JOURNEY</span><strong>{Math.round(step/8*100)}%</strong></div><div className="journey-bar"><i style={{width:`${Math.round(step/8*100)}%`}}/></div><div className="journey-steps">{labels.map((x,i)=><button key={x} disabled={i>step} className={i<=step?'active':''} onClick={()=>jump(i)}><em>{String(i+1).padStart(2,'0')}</em>{x}</button>)}</div></section>}
function Home({onSearch}:{onSearch:()=>void}){const submit=(e:FormEvent)=>{e.preventDefault();onSearch()};return <><section className="hero"><div><span className="eyebrow">INTERCITY, REFINED</span><h1>Move through the island with context.</h1><p>Choose your route, exact seat and boarding pass while Encore keeps the trip, vehicle and status connected.</p><div className="hero-metrics"><span><b>38</b> destinations</span><span><b>96%</b> on-time</span><span><b>420+</b> departures</span></div></div><div className="orbit"><i></i><b>BUS 203</b><span>SDQ</span><span>STI</span></div></section><form className="search-console" onSubmit={submit}><Field label="From" value="Santo Domingo"/><button type="button">⇄</button><Field label="To" value="Santiago"/><Field label="Date" value="2026-09-14" type="date"/><Field label="Passengers" value="2" type="number"/><button className="primary">SEARCH DEPARTURES →</button></form><div className="home-tech"><article><span>LIVE ROUTE</span><h3>Trip EN-001 is on schedule.</h3><p>Route, vehicle and arrival context remain visible through the flow.</p></article><article><span>DIGITAL BOARDING</span><h3>One pass. One trip identity.</h3></article><article><span>SEAT LEVEL</span><h3>Choose the real place you want.</h3></article></div></>}
function Field({label,value,type='text'}:{label:string;value:string;type?:string}){return <label><span>{label}</span><input type={type} defaultValue={value}/></label>}
function PageHead({eyebrow,title,onBack}:{eyebrow:string;title:string;onBack:()=>void}){return <div className="page-head"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1></div><button className="ghost" onClick={onBack}>← BACK</button></div>}
function Results({onBack,onSelect}:{onBack:()=>void;onSelect:(t:Trip)=>void}){return <><PageHead eyebrow="AVAILABLE DEPARTURES" title="Choose the rhythm of your day." onBack={onBack}/><LiveMap/><div className="insight-row"><Insight label="Fastest" value="2h 15m"/><Insight label="Best availability" value="18 seats"/><Insight label="Status" value="On schedule"/></div><div className="departures">{trips.map(t=><article key={t.id} className={`departure ${t.featured?'featured':''}`}><div><span>{t.id}</span><h3>{t.origin} → {t.destination}</h3><div className="times"><b>{t.departure}</b><i></i><small>{t.duration}</small><i></i><b>{t.arrival}</b></div><p>{t.bus} · Wi-Fi · A/C · Luggage</p></div><aside><strong>{money(t.price)}</strong><button className="primary" onClick={()=>onSelect(t)}>SELECT →</button></aside></article>)}</div></>}
function LiveMap(){return <div className="live-map"><iframe title="Encore route" src="https://www.openstreetmap.org/export/embed.html?bbox=-70.85%2C18.35%2C-69.80%2C19.60&layer=mapnik&marker=18.4822%2C-69.9369"></iframe><svg viewBox="0 0 1000 620" preserveAspectRatio="none"><path d="M160,485 C300,430 360,330 460,320 C570,309 620,220 700,190 C770,163 810,133 850,112"/></svg><div className="map-status"><i></i><strong>BUS 203</strong><span>On schedule · ETA 10:45</span></div><button className="map-expand" onClick={()=>document.querySelector('.live-map')?.classList.toggle('expanded')}>⛶ Expand map</button></div>}
function Insight({label,value}:{label:string;value:string}){return <article><span>{label}</span><strong>{value}</strong></article>}
function TripScreen({trip,onBack,onNext}:{trip:Trip;onBack:()=>void;onNext:()=>void}){return <><PageHead eyebrow={`${trip.id} · PREMIUM COACH`} title={`${trip.origin} to ${trip.destination}`} onBack={onBack}/><LiveMap/><div className="facts"><Fact label="Boarding" value="Agora Mall · North entrance"/><Fact label="Vehicle" value={`${trip.bus} · A874512`}/><Fact label="Driver" value="Ricardo Luna"/><Fact label="Service" value="Wi-Fi · A/C · Luggage"/></div><div className="action-band"><div><span>FARE PER PASSENGER</span><strong>{money(trip.price)}</strong></div><button className="primary" onClick={onNext}>CHOOSE SEATS →</button></div></>}
function Fact({label,value}:{label:string;value:string}){return <article><span>{label}</span><strong>{value}</strong></article>}
function SeatScreen({selected,toggle,onBack,onNext}:{selected:string[];toggle:(s:string)=>void;onBack:()=>void;onNext:()=>void}){return <><PageHead eyebrow="CABIN SELECTION" title="Choose your place on board." onBack={onBack}/><div className="seat-layout"><div className="coach"><div className="windshield">PANORAMIC FRONT <b>DRIVER</b></div><div className="legend"><span>○ Available</span><span>● Selected</span><span>◌ Occupied</span><span>◍ Reserved</span></div>{Array.from({length:10},(_,r)=><div className="seat-row" key={r}><em>{r+1}</em>{['A','B'].map(c=><SeatButton key={c} id={`${r+1}${c}`} selected={selected} toggle={toggle}/>)}<i className="aisle"></i>{['C','D'].map(c=><SeatButton key={c} id={`${r+1}${c}`} selected={selected} toggle={toggle}/>)}</div>)}<div className="rear">REAR · EMERGENCY EXIT</div></div><aside className="seat-summary"><span className="eyebrow">YOUR SELECTION</span><h2>{selected.length}/2 seats</h2><div className="seat-tags">{selected.map(x=><b key={x}>{x}</b>)}</div><p>Seats are held for 08:00 minutes.</p><button className="primary" disabled={selected.length!==2} onClick={onNext}>CONTINUE →</button></aside></div></>}
function SeatButton({id,selected,toggle}:{id:string;selected:string[];toggle:(s:string)=>void}){const occupied=['3B','5C','6B','9A'].includes(id),reserved=id==='7D';return <button disabled={occupied||reserved} className={`seat ${selected.includes(id)?'selected':''} ${occupied?'occupied':''} ${reserved?'reserved':''}`} onClick={()=>toggle(id)}><span className="seat-back">◉</span><span className="seat-base"></span><b>{id}</b></button>}
function Passengers({onBack,onNext}:{onBack:()=>void;onNext:()=>void}){return <><PageHead eyebrow="PASSENGER DETAILS" title="Who is travelling?" onBack={onBack}/><div className="smart-banner"><b>Smart validation</b><span>Passenger details are linked to seats and boarding pass.</span></div><form className="passenger-form" onSubmit={e=>{e.preventDefault();onNext()}}>{[1,2].map(i=><article className="passenger-card" key={i}><div className="passenger-no">0{i}</div><div className="fields"><Field label="Full name" value={i===1?'Maria Torres':''}/><Field label="Document" value={i===1?'001-7482110-4':''}/><Field label="Phone" value={i===1?'+1 809 555 1842':''}/><Field label="Email" value={i===1?'maria.torres@mail.com':''}/></div></article>)}<button className="primary wide">REVIEW TRIP →</button></form></>}
function Review({trip,seats,onBack,onNext}:{trip:Trip;seats:string[];onBack:()=>void;onNext:()=>void}){return <><PageHead eyebrow="REVIEW" title="Everything in one clear view." onBack={onBack}/><div className="review-grid"><div className="review-card"><Fact label="Route" value={`${trip.origin} → ${trip.destination}`}/><Fact label="Passengers" value="Maria Torres · Passenger 2"/><Fact label="Seats" value={seats.join(', ')}/><Fact label="Vehicle" value={`${trip.bus} · Premium Coach`}/></div><aside className="total-panel"><span>TOTAL</span><strong>{money(trip.price*2+35)}</strong><small>Fare + service fee</small><button className="primary" onClick={onNext}>CONTINUE TO PAY →</button></aside></div></>}
function Payment({method,setMethod,state,setState,onBack,onNext}:{method:string;setMethod:(m:string)=>void;state:'ready'|'checking'|'approved';setState:(s:'ready'|'checking'|'approved')=>void;onBack:()=>void;onNext:()=>void}){const verify=()=>{setState('checking');setTimeout(()=>setState('approved'),1000)};return <><PageHead eyebrow="PAYMENT" title="Secure your seats." onBack={onBack}/><div className="payment-grid"><div className="payment-form"><div className="pay-tabs">{['Card','CardNet','VisaNet'].map(m=><button type="button" key={m} className={method===m?'active':''} onClick={()=>setMethod(m)}>{m}</button>)}</div><Field label="Cardholder" value="Maria Torres"/><Field label="Card number" value="4821 0000 0000 4821"/><div className="two"><Field label="Expiry" value="09/29"/><Field label="CVV" value="***"/></div><div className={`verify ${state}`}><b>{state==='approved'?'✓ Card verified':state==='checking'?'Verifying card…':'Ready to verify'}</b><span>Secure payment simulation for the preview.</span></div>{state!=='approved'?<button className="primary wide" onClick={verify}>{state==='checking'?'VERIFYING…':'VERIFY CARD'}</button>:<button className="primary wide" onClick={onNext}>CONFIRM BOOKING →</button>}</div><div className={`credit-card ${state}`}><span>ENCORE</span><strong>•••• •••• •••• 4821</strong><div><b>MARIA TORRES</b><b>09/29</b></div><i></i></div></div></>}
function Confirmation({onBack,onTicket}:{onBack:()=>void;onTicket:()=>void}){return <><PageHead eyebrow="CONFIRMED" title="Your journey is ready." onBack={onBack}/><div className="confirmation"><div>✓</div><h2>Seats 4B and 4C are reserved.</h2><p>Your booking is connected to EN-001, Bus 203 and your digital boarding pass.</p><button className="primary" onClick={onTicket}>VIEW BOARDING PASS →</button></div></>}
function Ticket({seats,onBack}:{seats:string[];onBack:()=>void}){return <><PageHead eyebrow="DIGITAL BOARDING PASS" title="Ready to board." onBack={onBack}/><div className="ticket"><header><span>ENCORE TRANSPORT</span><strong>EN-001</strong><b>BOARDING</b></header><div className="ticket-route"><strong>08:30 <small>SDQ</small></strong><i></i><em>BUS</em><i></i><strong>10:45 <small>STI</small></strong></div><div className="ticket-body"><div className="qr">{Array.from({length:64},(_,i)=><i key={i} className={[0,1,2,4,5,6,7,8,10,12,13,14,16,17,19,21,22,23,24,26,28,29,30,31,33,35,36,38,39,40,42,44,45,47,48,49,51,53,55,56,57,58,60,62,63].includes(i)?'on':''}/>)}</div><div><Fact label="Passenger" value="Maria Torres"/><Fact label="Seats" value={seats.join(', ')}/><Fact label="Vehicle" value="Bus 203 · A874512"/></div></div></div></>}
