import type { AuthResponse, Booking, BookingPassengerInput, Driver, Incident, MapJourney, Passenger, Quote, Route, Seat, Trip, TripSearchFilters, User, Vehicle } from '@encore/types';

export class ApiError extends Error { constructor(public status:number,message:string,public payload:unknown=null){super(message);this.name='ApiError';} }
export interface EncoreApiClientOptions{baseUrl?:string;token?:string|null;}
export class EncoreApiClient{
  private baseUrl:string;private token:string|null;
  constructor(options:EncoreApiClientOptions={}){this.baseUrl=(options.baseUrl??'/api/v1').replace(/\/$/,'');this.token=options.token??null;}
  setToken(token:string|null){this.token=token;}getToken(){return this.token;}
  private async request<T>(path:string,init:RequestInit={}):Promise<T>{const headers=new Headers(init.headers);headers.set('Accept','application/json');if(init.body&&!headers.has('Content-Type'))headers.set('Content-Type','application/json');if(this.token)headers.set('Authorization',`Bearer ${this.token}`);let response:Response;try{response=await fetch(`${this.baseUrl}${path}`,{...init,headers});}catch(error){throw new ApiError(0,'Unable to reach Encore Transport.',error);}const payload=response.status===204?null:await response.json().catch(()=>null);if(!response.ok){const message=(payload as any)?.errors?Object.values((payload as any).errors).flat().join(' '):(payload as any)?.message;throw new ApiError(response.status,message??`Request failed (${response.status})`,payload);}return payload as T;}
  login(email:string,password:string){return this.request<AuthResponse>('/auth/login',{method:'POST',body:JSON.stringify({email,password})}).then(r=>(this.token=r.token,r));}
  register(payload:{name:string;email:string;phone?:string;password:string;password_confirmation:string}){return this.request<AuthResponse>('/auth/register',{method:'POST',body:JSON.stringify(payload)}).then(r=>(this.token=r.token,r));}
  me(){return this.request<{user:User}>('/auth/me');}async logout(){const r=await this.request<{message:string}>('/auth/logout',{method:'POST'});this.token=null;return r;}
  routes(){return this.request<{data:Route[]}>('/routes');}route(id:number|string){return this.request<{data:Route}>(`/routes/${id}`);}
  searchTrips(filters:TripSearchFilters){const p=new URLSearchParams();if(filters.origin)p.set('origin',filters.origin);if(filters.destination)p.set('destination',filters.destination);if(filters.date)p.set('date',filters.date);p.set('passengers',String(filters.passengers||1));return this.request<{data:Trip[]}>(`/trips/search?${p}`);}
  trip(id:number|string){return this.request<{data:Trip}>(`/trips/${id}`);}seats(id:number|string){return this.request<{data:(Seat&{row_number?:number|null;position_index?:number|null;accessible?:boolean;blocked?:boolean})[]}>(`/trips/${id}/seats`);}quote(id:number|string,passengers:number){return this.request<{data:Quote}>(`/trips/${id}/quote?passengers=${passengers}`);}mapJourney(origin:string,destination:string){const p=new URLSearchParams({origin,destination});return this.request<{data:MapJourney}>(`/maps/journey?${p}`);}
  bookings(){return this.request<{data:Booking[]}>('/bookings');}booking(id:number|string){return this.request<{data:Booking}>(`/bookings/${id}`);}createBooking(tripId:number|string,seatIds:number[],passengers:BookingPassengerInput[]){return this.request<{data:Booking}>('/bookings',{method:'POST',body:JSON.stringify({trip_id:Number(tripId),seat_ids:seatIds,passengers})});}cancelBooking(id:number|string){return this.request<{data:Booking}>(`/bookings/${id}/cancel`,{method:'POST'});}initiatePayment(id:number|string,idempotencyKey:string){return this.request(`/bookings/${id}/payments`,{method:'POST',body:JSON.stringify({idempotency_key:idempotencyKey})});}ticket(id:number|string){return this.request(`/bookings/${id}/ticket`);}
}
export const createEncoreApiClient=(options:EncoreApiClientOptions={})=>new EncoreApiClient(options);
export type { Driver, Incident, Passenger, Route, Trip, Vehicle };
